#!/bin/sh

#SBATCH -N 1        # Allocate 1 nodes for the job
#SBATCH -c 20       # Idun 20 cores
#SBATCH -t 32:00:00 # Upper time limit for the job (DD-HH:MM:SS)
#SBATCH --partition=CPUQ
#SBATCH --mem=32G              # 32 gigabytes memory
#SBATCH --job-name="rod_test"
#SBATCH --output=rod_test.txt
WORKDIR=${SLURM_SUBMIT_DIR}
cd ${WORKDIR}

#module load intel/2023b
module load Anaconda3/2022.10

if [ $# -eq 0 ]; then
	echo "No file arguments"
	exit 1
fi

file_path=$1

source ./venv/bin/activate
python $file_path
